export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '@/styles/globals.css'
import { Sidebar } from './components/sidebar/Sidebar'
import Header from './components/header/Header'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const items = [
    { label: 'Home', href: '/' },
    { label: 'Dashboard', href: '/dashboard' },
  ]

  return (
    <html lang="en">
      <body>
        <div style={{display: 'flex', minHeight: '100vh'}}>
          <Sidebar items={items} />
          <main style={{flex: 1, padding: '2rem'}}>
            <header className="page-header" style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
              <h1 style={{margin:0}}>Rick and Morty</h1>
              <Header />
            </header>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
